export const helpTopics = [
  { slug: "creating-a-campaign", name: "Creating a campaign", short: "Start, write your story and publish", description: "Start a fundraiser, write your story and publish your page.", icon: "plus" },
  { slug: "sharing-and-visibility", name: "Sharing and visibility", short: "Links, Public and Private", description: "Links, Public and Private campaigns.", icon: "share" },
  { slug: "bank-transfers", name: "Receiving support", short: "Bank transfers and where money goes", description: "Bank transfers and where your money goes.", icon: "bank" },
  { slug: "managing-campaigns", name: "Managing campaigns", short: "Edit, update, end or delete", description: "Edit, update, end or delete a campaign.", icon: "folder" },
  { slug: "account-and-privacy", name: "Account and privacy", short: "Profile, sign-in and your data", description: "Profile, sign-in and your information.", icon: "user" },
];

const article = (topic, slug, title, summary, paragraphs, extra = {}) => ({ topic, slug, title, summary, intro: summary, paragraphs, ...extra });

export const helpArticles = [
  article("creating-a-campaign", "create-and-publish", "How do I create and publish a campaign?", "Four steps take you from an idea to a page you can share.", ["Choose Create campaign, add a title, category, goal amount and end date, then upload a cover image. A wide image works best because the cover appears at a 16:7 shape; 1600 × 700 pixels is recommended.", "Build your story using text, sections, photos and video links. Preview the page on desktop and mobile, then go back and edit anything that needs work.", "Before publishing, add a bank account and choose it as your receiving method. Choose Public or Private visibility, review the hosting fee, accept the Publish Terms and publish. Your page goes live without waiting for manual approval. Fundu may review or remove it later if it is reported or violates our Terms."], { steps: ["Add the basics", "Tell your story", "Preview your page", "Publish"], tip: "Your work is saved as you go. Find an unfinished campaign under Drafts in My campaigns.", note: "During the current early-access period, the hosting fee is reduced to ₦0. No hosting payment is collected." }),
  article("creating-a-campaign", "writing-your-story", "Writing a story that helps people give", "What to include, and how to use blocks and photos.", ["Explain what happened, what you need support for, and how you plan to use the money. Clear details help supporters understand your goal.", "Use story blocks to add sections, text, photos or video links. You can return to your draft and revise the story before publishing."]),
  article("creating-a-campaign", "goal-and-end-date", "Choosing a goal and end date", "Set an amount you can explain and decide how long to run.", ["Enter a goal greater than zero and choose a future end date in Basics. Explain in your story what the amount will cover.", "The campaign page displays your goal and end date. The amount raised is updated by the organizer, so it may differ from bank transfers received." ]),
  article("creating-a-campaign", "cover-and-photos", "Adding a cover image and photos", "How images appear on your campaign page.", ["Add a cover image in Basics. It appears in a wide 16:7 frame on your page; 1600 × 700 pixels is a useful starting size.", "Add photos to story blocks when they help explain your fundraiser. Preview on both desktop and mobile to check how the images crop and appear." ]),
  article("creating-a-campaign", "after-publishing", "What happens when you publish", "Visibility, your link, and what supporters can see.", ["Your published campaign gets a shareable link. Public campaigns can appear on Explore; Private campaigns stay off Explore, but anyone with their link can view and share them.", "Supporters use the receiving information you selected to send money directly to you. Fundu does not receive or hold contributions. Fundu may review a campaign later if it is reported or violates the Terms." ]),
  article("creating-a-campaign", "drafts", "Saving and finishing drafts", "Where to find your unfinished campaign.", ["Your work is saved as you go. Leave the campaign creation flow and return to My campaigns to find it under Drafts.", "Open the draft to finish its details, preview it and publish when you are ready. A receiving method is needed before publishing." ]),
  article("sharing-and-visibility", "public-vs-private", "What’s the difference between Public and Private?", "Choose whether your campaign appears on Explore.", ["A Public campaign can be discovered on Explore and opened by anyone with its link.", "A Private campaign is hidden from Explore. Anyone with its link can still view and share it, so Private does not mean confidential. You can change visibility in your campaign settings." ]),
  article("sharing-and-visibility", "sharing-your-link", "Sharing your campaign link", "Help supporters find the right page.", ["After publishing, open your campaign and copy its link to share with people you trust. Check that it opens the correct page before sending it widely.", "Private campaigns can be reached by anyone who has the link. If you want public discovery, choose Public visibility." ]),
  article("sharing-and-visibility", "supporter-view", "What supporters see on your page", "Understand the public campaign page.", ["Supporters can see your campaign story, goal, updates and selected receiving information. They can use those details to send support directly to you.", "The amount raised is reported by the organizer and is not verified by Fundu. Supporters must sign in to comment." ]),
  article("bank-transfers", "where-money-goes", "Where does a supporter’s money go?", "Support goes directly to the organizer’s bank account.", ["In the current Nigerian beta, Fundu supports direct bank transfers. Supporters send money to the bank account selected by the campaign organizer. Fundu does not receive, hold or process these contributions.", "If you sent money to the wrong account, contact your bank as soon as possible. For a refund from an organizer, contact the organizer directly. Fundu cannot reverse a bank transfer." ]),
  article("bank-transfers", "how-to-support", "How to support a campaign", "Check the campaign and send a bank transfer.", ["Read the campaign page and check the organizer’s receiving details before sending money. Use your bank’s normal transfer process to send support directly to the organizer.", "Fundu never asks for your bank password, PIN or one-time code. If a campaign looks misleading, use its report option or contact support." ]),
  article("bank-transfers", "bank-details", "Adding or changing bank details", "Keep your receiving information accurate.", ["Add a bank account in Payment methods before publishing a campaign, then select it as the campaign’s receiving method.", "To change bank information, open Payment methods from Settings. Check your campaign’s selected receiving information after any change so supporters see the details you intend." ]),
  article("bank-transfers", "organizer-reported-amount", "Why is the amount raised reported by the organizer?", "Fundu cannot see or verify direct bank transfers.", ["Because supporters pay organizers directly, Fundu cannot automatically track the total received. The organizer enters and updates the amount shown on the campaign.", "Treat that figure as organizer-reported, not a bank-verified balance. If something seems wrong, report the campaign." ]),
  article("managing-campaigns", "amount-raised", "Updating the amount raised", "Keep supporters informed about your progress.", ["Open your campaign in My campaigns and update the amount raised as support arrives in your bank account. The displayed figure is organizer-reported and Fundu does not verify it.", "Check your bank’s records before changing the number so the progress shown to supporters is accurate." ]),
  article("managing-campaigns", "posting-updates", "Posting updates", "Tell supporters what has changed.", ["Open your campaign and post an update when you have progress to share. Updates can explain milestones, changes to your plans or what the support has achieved.", "Keep your updates factual. They remain part of the campaign story when a campaign ends." ]),
  article("managing-campaigns", "editing", "Editing a campaign", "Revise campaign information while it is active.", ["Open the campaign from My campaigns and choose Edit to revise its details, story, media or visibility. Preview the page again after making changes.", "Check the receiving information shown to supporters whenever you edit payment details." ]),
  article("managing-campaigns", "ending-early", "Ending a campaign early", "Stop asking for support while keeping the story visible.", ["Open the campaign in My campaigns and choose the option to end it. Its story and updates remain visible, but the page stops asking for support.", "The current app also offers a restart flow for an ended campaign. It asks you to choose a new future end date before restarting." ]),
  article("managing-campaigns", "deleting", "Deleting a campaign or draft", "Understand what removal means before you confirm.", ["Find the campaign in My campaigns and use its delete action. Read the confirmation carefully: removing a campaign can make its public link stop working.", "If you only want to stop asking for support, ending the campaign may be a better fit because its story and updates stay visible." ]),
  article("managing-campaigns", "hosting-fees", "Hosting fees and discount codes", "How early-access hosting is priced.", ["Fundu’s standard hosting price is ₦100 per day for the days your campaign runs. A discount code can reduce the amount due.", "During the current early-access period, the hosting fee is reduced to ₦0, so no hosting payment is collected." ]),
  article("account-and-privacy", "signing-in", "Signing in with email or Google", "Choose how to access your Fundu account.", ["Use the sign-in page to enter your email and password, or choose Google sign-in. If you signed up by email, verify your address using the message sent to your inbox.", "Use the same sign-in method and email when returning to your account." ]),
  article("account-and-privacy", "password-reset", "Resetting your password", "Get back into an email-and-password account.", ["On the sign-in page, choose Forgot password and enter the email for your account. Follow the reset link sent to that inbox.", "If you sign in with Google, use your Google account to authenticate. Never share a password or reset link with anyone." ]),
  article("account-and-privacy", "editing-profile", "Editing your profile", "Change how you appear on Fundu.", ["Open Settings, choose Profile and then Edit profile. You can update your name, photo, display name, country and bio.", "Your name, photo and bio may appear on your public campaign pages as the organizer. Your sign-in email is not shown on campaigns." ]),
  article("account-and-privacy", "deleting-account", "Deleting your account", "Understand what is removed and how to confirm.", ["Open Settings, then Sign-in and security, and choose Delete my account. The confirmation flow explains that your profile, campaigns and receiving methods will be removed and campaign links will stop working.", "This cannot be undone. If you cannot complete deletion, contact Fundu support at funduhelp@gmail.com." ]),
  article("account-and-privacy", "reporting", "Reporting a campaign", "Tell Fundu about a campaign that concerns you.", ["Use Report a campaign on the public campaign page. Include the campaign link and explain what concerns you so the team can review it.", "If you sent money directly to an organizer and need a refund, contact the organizer. For a mistaken transfer, contact your bank promptly." ]),
  article("account-and-privacy", "your-information", "How Fundu handles your information", "Read about the information Fundu collects and uses.", ["The Privacy Policy explains what information Fundu collects, why it is used, who can see campaign details and how to make a privacy request.", "Read the full Privacy Policy for details. You can contact funduhelp@gmail.com with privacy questions." ], { link: { href: "/privacy", text: "Read the Privacy Policy" } }),
];

helpArticles[0].stepDetails = [
  "Choose Create campaign. Add a title, category, goal amount and future end date, then upload a cover image. A wide image works best because the cover appears at a 16:7 shape; 1600 × 700 pixels is recommended.",
  "Build your story with sections, text, photos and video links. Explain what happened, what the money is for and how you plan to use it.",
  "Check what supporters will see on desktop and mobile. Go back and edit anything that is unclear.",
  "Add a bank account as your receiving method. Choose Public or Private visibility, review the hosting fee, accept the Publish Terms and publish.",
];

export const helpFaqs = [
  ["How do I create and publish a campaign?", "Create a campaign through Basics, Story, Preview and Publish. Add a bank account as your receiving method before publishing.", "creating-a-campaign/create-and-publish"],
  ["Where does a supporter’s money go?", "Support goes directly to the organizer’s selected bank account. Fundu does not hold contributions.", "bank-transfers/where-money-goes"],
  ["Why is the amount raised reported by the organizer?", "Fundu cannot see direct transfers, so the organizer updates the amount shown. It is not verified by Fundu.", "bank-transfers/organizer-reported-amount"],
  ["What’s the difference between Public and Private?", "Public campaigns can appear on Explore. Private ones are hidden there, but anyone with the link can view them.", "sharing-and-visibility/public-vs-private"],
  ["How do I change my bank details?", "Open Settings, then Payment methods. Check the receiving method selected on your campaign after editing it.", "bank-transfers/bank-details"],
  ["How do I edit, end or delete a campaign?", "Manage your campaign from My campaigns. End it to stop asking for support while leaving its story visible.", "managing-campaigns/editing"],
  ["What does hosting cost?", "The standard price is ₦100 per day. During early access, the hosting fee is reduced to ₦0.", "managing-campaigns/hosting-fees"],
  ["How do I report a campaign?", "Use Report a campaign on its public page and explain your concern.", "account-and-privacy/reporting"],
];

export const helpArticleUrl = (item) => `/help/${item.topic}/${item.slug}`;
export const getHelpTopic = (slug) => helpTopics.find((item) => item.slug === slug);
export const getHelpArticle = (topic, slug) => helpArticles.find((item) => item.topic === topic && item.slug === slug);
